//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMGame.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStock
    {
        public string UserID { get; set; }
        public string SectorID { get; set; }
        public string CompanyID { get; set; }
        public int StockQuantity { get; set; }
        public decimal StockPrice { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
